#!/bin/bash

APACHE2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok install")
if [ $APACHE2 -eg 0 ];
then

	echo "apache installeerimine"
	sudo apt-get install apache2 -y;
elif [ $APACHE2 -eq 1 ];
then

	echo "Apache on installeeritud"
	service apache2 status
fi
