#!/bin/bash

APACHE2=$(dpkg-query -W -f='${Status}' php7.0 2>/dev/null | grep -c "ok install")
if [ $APACHE2 -eq 0 ];
then

	echo "php installeerimine"
	sudo apt-get install php7.0 -y;
elif [ $APACHE2 -eq 1 ];
then

	echo "php on installeeritud"
	php -v
fi
