#!/bin/bash

APACHE2=$(dpkg-query -W -f='${Status}' phpmyadmin 2>/dev/null | grep -c "ok install")
if [ $APACHE2 -eq 0 ];
then

	echo "phpmyadmini installeerimine"
	sudo apt-get install phpmyadmin php-mbstring php-gettext -y;
	sudo phpenmod mcrypt;
	sudo phpenmod mbstring
elif [ $APACHE2 -eq 1 ];
then

	echo "phpmyadmin on installeeritud"
	service phpmyadmin status
fi
